/**
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SimpleInventoryApi);
  }
}(this, function(expect, SimpleInventoryApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SimpleInventoryApi.ServiceOrder();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ServiceOrder', function() {
    it('should create an instance of ServiceOrder', function() {
      // uncomment below and update the code to test ServiceOrder
      //var instane = new SimpleInventoryApi.ServiceOrder();
      //expect(instance).to.be.a(SimpleInventoryApi.ServiceOrder);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new SimpleInventoryApi.ServiceOrder();
      //expect(instance).to.be();
    });

    it('should have the property device (base name: "device")', function() {
      // uncomment below and update the code to test the property device
      //var instane = new SimpleInventoryApi.ServiceOrder();
      //expect(instance).to.be();
    });

    it('should have the property _date (base name: "date")', function() {
      // uncomment below and update the code to test the property _date
      //var instane = new SimpleInventoryApi.ServiceOrder();
      //expect(instance).to.be();
    });

    it('should have the property descriptionShort (base name: "description_short")', function() {
      // uncomment below and update the code to test the property descriptionShort
      //var instane = new SimpleInventoryApi.ServiceOrder();
      //expect(instance).to.be();
    });

    it('should have the property descriptionLong (base name: "description_long")', function() {
      // uncomment below and update the code to test the property descriptionLong
      //var instane = new SimpleInventoryApi.ServiceOrder();
      //expect(instance).to.be();
    });

  });

}));
